<a href="https://colab.research.google.com/github/CE334/CE334_230733_pankaj_kumar/blob/main/CE334_Lab0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

## **1. Row and Column Matrix**

*Input Method*

In [ ]:
n_r = int(input("Enter number of elements: ")) # int is used because the input will be string. so to convert it into interger.
entries = list(map(int, input("Enter the numbers separated by space: ").split()))  # split function will split the space seprated words then 'map' will map each substring with int datatype. then list will create list of the input numbers

# Create a numpy array and reshape it to (1, n)
row_matrix = np.array(entries).reshape(1, n_r)

print("\nRow Matrix:")
print(row_matrix)

In [ ]:
n_c = int(input("Enter number of elements: ")) # int is used because the input will be string. so to convert it into interger.
entries = list(map(int, input("Enter the numbers separated by space: ").split())) # split function will split the space seprated words then 'map' will map each substring with int datatype. then list will create list of the input numbers

# Create a numpy array and reshape it to (n, 1)
column_matrix = np.array(entries).reshape(n_c, 1)

print("\nColumn Matrix:")
print(column_matrix)

*Manual Method*

In [16]:
row_matrix = np.array([1,3,2]) #numpy library used to create matrix manually
print(row_matrix)

[1 3 2]


In [17]:
column_matrix = np.array([[1],[3],[2]]) #numpy library used to create matrix manually
print(column_matrix)

[[1]
 [3]
 [2]]


# **2. 5x5 Matrix**

*Manual Method*

In [19]:
matrix = np.array([[1,2,3,4,5],[2,3,4,5,5],[1,2,3,5,4],[1,3,3,4,5],[3,4,5,6,6]]) #numpy library used to create matrix manually
a = matrix
print("matrix a is:\n",a)

matrix a is:
 [[1 2 3 4 5]
 [2 3 4 5 5]
 [1 2 3 5 4]
 [1 3 3 4 5]
 [3 4 5 6 6]]


*Input Method*

In [ ]:
entries = list(map(int, input("Enter 25 numbers separated by space: ").split()))  # split function will split the space seprated words then 'map' will map each substring with int datatype. then list will create list of the input numbers

# Create a numpy array and reshape it to (5, 5)
matrix = np.array(entries).reshape(5,5)
a = matrix
print("\nMatrix a is:")
print(a)

# **3. Row**

In [20]:
third_row = a[2]  # it will extract third row as index starts with 0,1 and so on
print("third row is: ", third_row)

third row is:  [1 2 3 5 4]


# **4. Column**

In [21]:
fourth_column = a[:,3].reshape(-1,1)  # it will extract third column. the '-1' will automatically figure out number of row in matrix and '1' keep it column matrix
print("fourth column is:\n", fourth_column)

fourth column is:
 [[4]
 [5]
 [5]
 [4]
 [6]]


# **5.Matrix Sort**

*Row sorted matrix*

In [22]:
row_sorted = np.sort(a, axis = 1)  # we used axis for sorting purpose axis '0' is down the rows and axis'1' is across the columns
print("row-sorted matrix will be given by")
print(row_sorted)

row-sorted matrix will be given by
[[1 2 3 4 5]
 [2 3 4 5 5]
 [1 2 3 4 5]
 [1 3 3 4 5]
 [3 4 5 6 6]]


*Column Sorted matrix*

In [23]:
column_sorted = np.sort(a, axis = 0)  # we used axis for sorting purpose axis '0' is down the rows and axis'1' is across the columns
print("column sorted matrix will be given by")
print(column_sorted)

column sorted matrix will be given by
[[1 2 3 4 4]
 [1 2 3 4 5]
 [1 3 3 5 5]
 [2 3 4 5 5]
 [3 4 5 6 6]]


# **6. New Matrix**

In [24]:
b = a.copy()  #copy function will copy matrix a as it is
for i in range(b.shape[0]): # shape[0] will tell length in axis '0' that is no. of rows
    for j in range(b.shape[1]): # shape[1] will tell length in axis '0' that is no. of rows
        if b[i, j] > 2:
            b[i, j] *= 10
print("matrix b is ")
print(b)

matrix b is 
[[ 1  2 30 40 50]
 [ 2 30 40 50 50]
 [ 1  2 30 50 40]
 [ 1 30 30 40 50]
 [30 40 50 60 60]]


# **7. Addition**

In [25]:
sum_matrix = a+b
print("Addition of matrix a and b is \n")
print(sum_matrix)

Addition of matrix a and b is 

[[ 2  4 33 44 55]
 [ 4 33 44 55 55]
 [ 2  4 33 55 44]
 [ 2 33 33 44 55]
 [33 44 55 66 66]]


# **8. Subtract**

In [26]:
subtract_matrix = a-b
print("subtration of matrix b from a is\n")
print(subtract_matrix)

subtration of matrix b from a is

[[  0   0 -27 -36 -45]
 [  0 -27 -36 -45 -45]
 [  0   0 -27 -45 -36]
 [  0 -27 -27 -36 -45]
 [-27 -36 -45 -54 -54]]


# **9. Multiplicaiton**

*Element-wise Multiplication*

In [27]:
elm_mup_matrix = a*b # this will multiply corresponding number in both matrix
print("elementwise muliplication of matrix a and b is \n")
print(elm_mup_matrix)

elementwise muliplication of matrix a and b is 

[[  1   4  90 160 250]
 [  4  90 160 250 250]
 [  1   4  90 250 160]
 [  1  90  90 160 250]
 [ 90 160 250 360 360]]


*Matrix Multiplication*

In [28]:
mat_matrix = a@b  # this will peroform matrix multiplication
print("matrix multiplication of a and b is\n")
print(mat_matrix)

matrix multiplication of a and b is

[[ 162  388  570  750  770]
 [ 167  452  700  930  960]
 [ 133  378  550  730  760]
 [ 164  418  610  800  820]
 [ 202  556  880 1170 1210]]


## **10. Division of Matrix**

In [29]:
div_matrix_a = a/18
div_matrix_b = b/18
print("matrix a after division is:\n", div_matrix_a)
print("\nmatrix b after division is:\n", div_matrix_b)

matrix a after division is:
 [[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.11111111 0.16666667 0.22222222 0.27777778 0.27777778]
 [0.05555556 0.11111111 0.16666667 0.27777778 0.22222222]
 [0.05555556 0.16666667 0.16666667 0.22222222 0.27777778]
 [0.16666667 0.22222222 0.27777778 0.33333333 0.33333333]]

matrix b after division is:
 [[0.05555556 0.11111111 1.66666667 2.22222222 2.77777778]
 [0.11111111 1.66666667 2.22222222 2.77777778 2.77777778]
 [0.05555556 0.11111111 1.66666667 2.77777778 2.22222222]
 [0.05555556 1.66666667 1.66666667 2.22222222 2.77777778]
 [1.66666667 2.22222222 2.77777778 3.33333333 3.33333333]]


# **11. Matrix Operations**

*Inverse of matrix*

In [30]:
# Inverse (only if matrix is invertible)
a_inv = np.linalg.inv(a)   # linalg is short of linear algebra. here linalg module of numpy has used to perform complicated task
b_inv = np.linalg.inv(b)

print("Inverse of a:\n", a_inv)
print("\nInverse of b:\n", b_inv)

Inverse of a:
 [[ 1.00000000e+00 -4.50000000e+00  5.00000000e-01 -5.00000000e-01
   3.00000000e+00]
 [-1.00000000e+00 -1.06581410e-15  5.32907052e-16  1.00000000e+00
   1.06581410e-15]
 [-1.00000000e+00  7.50000000e+00 -1.50000000e+00 -5.00000000e-01
  -4.00000000e+00]
 [-1.77635684e-15 -2.00000000e+00  1.00000000e+00 -2.77555756e-16
   1.00000000e+00]
 [ 1.00000000e+00 -2.00000000e+00 -2.44249065e-15 -2.77555756e-16
   1.00000000e+00]]

Inverse of b:
 [[ 4.35540070e-04 -5.48780488e-02  6.09756098e-03  5.66202091e-03
   3.65853659e-02]
 [-3.57142857e-02 -3.09829681e-17  1.54914841e-17  3.57142857e-02
   9.68217754e-19]
 [ 6.54181185e-02  1.57317073e-01 -8.41463415e-02 -1.49564460e-01
  -4.87804878e-03]
 [-6.54616725e-02 -5.18292683e-02  8.35365854e-02  4.89982578e-02
   1.21951220e-03]
 [ 3.45383275e-02 -5.18292683e-02 -1.64634146e-02  4.89982578e-02
   1.21951220e-03]]


*Rank of matrix*

In [31]:
# rank of matrix mean how many independent equation it can give
print("Rank of a:", np.linalg.matrix_rank(a))  # linalg module of numpy had been used
print("Rank of b:", np.linalg.matrix_rank(b))

Rank of a: 5
Rank of b: 5


*Conditional Value*

In [32]:
print("Condition number of a:", np.linalg.cond(a))
print("Condition number of b:", np.linalg.cond(b))

Condition number of a: 206.64290964972562
Condition number of b: 50.90680197422883


*Singular Value Decomposition of matrix a and b*

In [33]:
Ua, Sa, Va = np.linalg.svd(a)
Ub, Sb, Vb = np.linalg.svd(b)
print(Ua, Sa, Va)
print("\n")
print(Ub, Sb, Vb)

[[-0.38389893  0.55066899  0.17790453  0.70522877  0.14278526]
 [-0.4638002  -0.21499147 -0.05618342  0.10197918 -0.85153491]
 [-0.38280111  0.29764634 -0.81855778 -0.26579073  0.15552629]
 [-0.40142577  0.37037202  0.53425625 -0.64505242  0.01263163]
 [-0.57430971 -0.65174654  0.09862469  0.07426501  0.4797423 ]] [19.14825775  1.56964644  1.23941639  0.57939254  0.09266351] [[-0.19942573 -0.33560844 -0.42986296 -0.56507301 -0.58609443]
 [-0.74318343 -0.2830025  -0.29473934  0.11910906  0.51626517]
 [ 0.06221496  0.44166817 -0.04098801 -0.75302756  0.48200415]
 [ 0.38167388 -0.78234285  0.28029117 -0.22914052  0.33346094]
 [ 0.50829333 -0.01206049 -0.80504869  0.21667865  0.21549802]]


[[-0.36791229 -0.56039707 -0.0749158  -0.67475994 -0.29947006]
 [-0.46660437  0.05629812  0.41880705  0.44411707 -0.63755122]
 [-0.3667034  -0.5715552  -0.31642874  0.53874278  0.38533406]
 [-0.41008226  0.11081454  0.65094565 -0.20473464  0.59490013]
 [-0.58675554  0.58637056 -0.54325951 -0.12368909  0

*Norm*

In [34]:
print("Norm of a:", np.linalg.norm(a)) # it is the square root of sum of square of each element of matrix
print("Norm of b:", np.linalg.norm(b))

Norm of a: 19.261360284258224
Norm of b: 188.7193683753737


## **12. Comlumn Vector Operation**

*Norm Calculation*

In [35]:
v = a[:,3].reshape(-1, 1)     #  the '-1' will automatically figure out number of row in matrix and '1' keep it column matrix
norm_v = np.linalg.norm(v)    # linalg module of numpy is used
print("Norm:", norm_v)

Norm: 10.862780491200215


*Inner Product*

In [36]:
inner_product = v.T @ v   # matrix muliplicaiton is performed with the transpose of matrix
print("Inner product:\n", inner_product)   # it is a number

Inner product:
 [[118]]


*Outer Product*

In [37]:
outer_product = v @ v.T
print("Outer product:\n", outer_product)# it is a matrix

Outer product:
 [[16 20 20 16 24]
 [20 25 25 20 30]
 [20 25 25 20 30]
 [16 20 20 16 24]
 [24 30 30 24 36]]


## **13. Derivative Function**

In [38]:
#chat gpt help had been taken to construct the function and compare the analytical values with numerical values
import math  #standered math library had been imported to implement mathematical function and operations

def derivative(f, a, method, h=0.01):
    """
    Compute the numerical derivative of function f at point a.

    Parameters:
    f      : function handle (e.g., math.exp)
    a      : point at which to compute the derivative
    method : 'forward', 'backward', or 'central' (default: 'central')
    h      : step size (default: 0.01)
    """
    if method == 'forward':
        return (f(a + h) - f(a)) / h
    elif method == 'backward':
        return (f(a) - f(a - h)) / h
    elif method == 'central':
        return (f(a + h) - f(a - h)) / (2 * h)
    else:
        raise ValueError("Method must be 'forward', 'backward', or 'central'")

# --- Testing the Function ---

x_val = 0.5

# Test 1: f(x) = e^x
# Analytical derivative of e^x is e^x. At x=0.5, exact value is e^0.5
exact_exp = math.exp(x_val)

print(f"--- Derivative of e^x at x = {x_val} ---") # here python f string is used to simplyfy the print operation
print(f"Exact Value: {exact_exp:.6f}")  # .6f will print 6 integer after decimal on output screen
print(f"Forward:     {derivative(math.exp, x_val, 'forward', h=0.01):.6f}") #------|
print(f"Backward:    {derivative(math.exp, x_val, 'backward', h=0.01):.6f}") #     |--numerical derivatives
print(f"Central:     {derivative(math.exp, x_val, 'central', h=0.01):.6f}") #------|

print("\n")

# Test 2: f(x) = cos(x)
# Analytical derivative of cos(x) is -sin(x). At x=0.5, exact value is -sin(0.5)
exact_cos = -math.sin(x_val)

print(f"--- Derivative of cos(x) at x = {x_val} ---")
print(f"Exact Value: {exact_cos:.6f}")
print(f"Forward:     {derivative(math.cos, x_val, 'forward', h=0.01):.6f}")
print(f"Backward:    {derivative(math.cos, x_val, 'backward', h=0.01):.6f}")
print(f"Central:     {derivative(math.cos, x_val, 'central', h=0.01):.6f}")

--- Derivative of e^x at x = 0.5 ---
Exact Value: 1.648721
Forward:     1.656992
Backward:    1.640505
Central:     1.648749


--- Derivative of cos(x) at x = 0.5 ---
Exact Value: -0.479426
Forward:     -0.483805
Backward:    -0.475030
Central:     -0.479418


# **14. Read CSV**

In [39]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [40]:
df = pd.read_csv('/content/drive/MyDrive/AWS.csv')  #used pandas to read csv file
print(df.head())   # it will print first five rows with headers

                  created_at  entry_id  Soil Temperature  Soil Moisture  \
0  2022-12-14T14:19:11+05:30     10830             21.06            817   
1  2022-12-14T14:20:13+05:30     10831             21.06            817   
2  2022-12-14T14:21:15+05:30     10832             21.06            817   
3  2022-12-14T14:22:18+05:30     10833             21.06            817   
4  2022-12-14T14:23:20+05:30     10834             21.06            817   

   Wind Speed  Rainfall  Temperature  Humidity  Pressure  Battery Voltage  
0         0.0      0.25        25.38     45.09      1.94             4.14  
1         0.0      0.25        25.27     46.52      1.94             4.14  
2         0.0      0.25        25.34     45.79      1.94             4.14  
3         0.0      0.25        25.13     44.91      1.94             4.15  
4         0.0      0.25        24.95     45.12      1.94             4.15  
